"""add submenu_count and dishes_count

Revision ID: 4b029583e7a2
Revises: bca96bad8ce3
Create Date: 2023-01-27 19:26:39.939272

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b029583e7a2'
down_revision = 'bca96bad8ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('submenus_count', sa.Integer(), default=0))
    op.add_column('menu', sa.Column('dishes_count', sa.Integer(), default=0))
    op.add_column(
        'submenu', sa.Column(
            'dishes_count', sa.Integer(), default=0,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'submenus_count')
    op.drop_column('menu', 'dishes_count')
    op.drop_column('submenu', 'dishes_count')

    # ### end Alembic commands ###
